package de.fau.cs.mad.fly.levelLoader;

import com.badlogic.gdx.math.Vector3;

/**
 * Child class of {@link RawLevel} that contains all functions and containers to
 * extract the information out of its parent to load level in the 3D world.
 * 
 * @author Lukas Hahmann
 * 
 */
public class Level extends RawLevel {
	/**
	 * Radius of the Level which defines the outer boundary which should be
	 * never reached by the user.
	 */
	public float radius = 0.0f;

	/**
	 * Calculates the {@link #radius} of the Level as a sum of the length of all
	 * sections. To make sure the radius can never be reached, the final result
	 * is increased by 10 %.
	 */
	public void calculateRadius() {
		radius = super.firstSection.length;
		for (Section section : super.sections) {
			radius += section.length;
		}
		radius *= 1.1;
	}

	/**
	 * Getter for the starting position of the level
	 * 
	 * @return Vector3 with the starting position of the level
	 */
	public Vector3 getCameraStartPosition() {
		return new Vector3(startingPointX, startingPointY, startingPointZ);
	}

	/**
	 * Returns the point, the camera is looking at in the beginning. This point
	 * is generated by adding the starting position and the direction vector of
	 * the first section.
	 */
	public Vector3 getCameraLookAt() {
		Vector3 lookAt = new Vector3(startingPointX, startingPointY,
				startingPointZ);
		if (firstSection != null) {
			lookAt.add(firstSection.directionX, firstSection.directionY,
					firstSection.directionZ);
		}
		return lookAt;
	}

	@Override
	public String toString() {
		StringBuilder stringBuilder = new StringBuilder("Level: ");
		stringBuilder.append("radius: " + radius + ",\n");
		stringBuilder.append("extends RawLevel: " + super.toString());
		return stringBuilder.toString();
	}
}
